import { useEffect, useMemo, useState, type FormEvent } from "react";
import { api } from "./api";

type Page = "Dashboard" | "Customers" | "Jobs" | "Catalog" | "Estimates" | "Backups" | "Settings";
type Customer = { id: string; displayId: string; name: string; email?: string; phone?: string };
type Job = { id: string; display_id: string; customer_id: string; customer_name: string; name: string; scope?: string; status: string };
type CatalogItem = { id: string; description: string; unit: string; defaultPriceCents: number; active: boolean };
type Estimate = { id: string; displayId: string; generatedAt: string; totalCents: number; jobId: string };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const nav: Page[] = ["Dashboard", "Customers", "Jobs", "Catalog", "Estimates", "Backups", "Settings"];

export function App() {
  const [page, setPage] = useState<Page>("Dashboard");
  const [customers, setCustomers] = useState<Customer[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [catalog, setCatalog] = useState<CatalogItem[]>([]); const [estimates, setEstimates] = useState<Estimate[]>([]);
  const [dashboard, setDashboard] = useState({ counts: { customers: 0, openJobs: 0, estimates: 0, monthTotalCents: 0 }, recent: [] as Array<{ displayId: string; customerName: string; jobName: string; totalCents: number }> });
  const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const [d, c, j, cat, e] = await Promise.all([api<typeof dashboard>("/dashboard"), api<{data: Customer[]}>("/customers"), api<{data: Job[]}>("/jobs"), api<{data: CatalogItem[]}>("/catalog"), api<{data: Estimate[]}>("/estimates")]); setDashboard(d); setCustomers(c.data); setJobs(j.data); setCatalog(cat.data); setEstimates(e.data); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load data"); } };
  useEffect(() => { void refresh(); }, []);
  const title = useMemo(() => page === "Dashboard" ? "Good afternoon, Kevin" : page, [page]);
  return <div className="shell"><aside><div className="logo"><span>PA</span><div>PRO ANGLE<small>CONSTRUCTION</small></div></div><nav>{nav.map((item) => <button key={item} className={page === item ? "active" : ""} onClick={() => setPage(item)}><i>{icons[item]}</i>{item}</button>)}</nav><div className="profile"><div className="avatar">KE</div><div><strong>Kevin Edinger</strong><small>Administrator</small></div></div></aside><main><header><div><p className="eyebrow">PRO ANGLE WORKSPACE</p><h1>{title}</h1></div><div className="status"><span></span>Protected by Cloudflare Access</div></header>{notice && <div className="notice" onClick={() => setNotice("")}>{notice}</div>}{page === "Dashboard" && <Dashboard data={dashboard} setPage={setPage} />}{page === "Customers" && <Customers customers={customers} busy={busy} submit={async (values) => run(setBusy, setNotice, async () => { await api("/customers", { method: "POST", body: JSON.stringify(values) }); await refresh(); })} />}{page === "Jobs" && <Jobs jobs={jobs} customers={customers} catalog={catalog} busy={busy} notify={setNotice} submit={async (values) => run(setBusy, setNotice, async () => { await api("/jobs", { method: "POST", body: JSON.stringify(values) }); await refresh(); })} />}{page === "Catalog" && <Catalog items={catalog} busy={busy} submit={async (values) => run(setBusy, setNotice, async () => { await api("/catalog", { method: "POST", body: JSON.stringify(values) }); await refresh(); })} />}{page === "Estimates" && <Estimates estimates={estimates} />}{page === "Backups" && <Backups />}{page === "Settings" && <Settings />}</main></div>;
}

async function run(setBusy: (v:boolean)=>void, setNotice:(v:string)=>void, action:()=>Promise<void>) { setBusy(true); try { await action(); setNotice("Saved successfully."); } catch (e) { setNotice(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); } }
const icons: Record<Page,string> = { Dashboard:"⌂", Customers:"♙", Jobs:"▣", Catalog:"◇", Estimates:"▤", Backups:"↧", Settings:"⚙" };
function Dashboard({data,setPage}:{data: ReturnTypeDashboard; setPage:(p:Page)=>void}) { const cards = [["Active customers",data.counts.customers,"Customers"],["Open jobs",data.counts.openJobs,"Jobs"],["Estimate versions",data.counts.estimates,"Estimates"],["Last 30 days",money(data.counts.monthTotalCents),"Estimates"]] as const; return <><section className="metrics">{cards.map(([label,value,target],i)=><button key={label} onClick={()=>setPage(target)}><span className={`metric-icon c${i}`}>{icons[target]}</span><small>{label}</small><strong>{value}</strong><em>View details →</em></button>)}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">LATEST ACTIVITY</p><h2>Recent estimates</h2></div><button className="secondary" onClick={()=>setPage("Estimates")}>View all</button></div>{data.recent.length ? <div className="table">{data.recent.map((row)=><div className="tr" key={row.displayId}><div><strong>{row.displayId}</strong><small>{row.customerName} · {row.jobName}</small></div><b>{money(row.totalCents)}</b><span className="pill">Final</span></div>)}</div> : <Empty title="No estimates yet" text="Create a customer and job to prepare the first estimate." />}</section><section className="welcome"><div><p className="eyebrow">QUICK START</p><h2>From first call to signed-off estimate</h2><p>Build a reusable catalog, snapshot pricing into a job, and issue immutable estimate versions in PDF, spreadsheet, or CSV.</p></div><button onClick={()=>setPage("Customers")}>Add first customer</button></section></> }
type ReturnTypeDashboard = {counts:{customers:number;openJobs:number;estimates:number;monthTotalCents:number};recent:Array<{displayId:string;customerName:string;jobName:string;totalCents:number}>};
function Customers({customers,busy,submit}:{customers:Customer[];busy:boolean;submit:(v:object)=>Promise<void>}) { return <Grid title="Customer directory" form={<SimpleForm busy={busy} fields={["name","email","phone","address"]} submit={submit} />} rows={customers.map(c=>[c.displayId,c.name,c.email||"—",c.phone||"—"])} headers={["ID","Customer","Email","Phone"]}/> }
function Jobs({jobs,customers,catalog,busy,submit,notify}:{jobs:Job[];customers:Customer[];catalog:CatalogItem[];busy:boolean;submit:(v:object)=>Promise<void>;notify:(v:string)=>void}) { const [selected,setSelected]=useState(""); const job=jobs.find(j=>j.id===selected); return <><Grid title="Jobs" form={<SimpleForm busy={busy} fields={["customerId","name","address","scope"]} selects={{customerId:customers.map(c=>[c.id,`${c.displayId} · ${c.name}`])}} submit={submit}/>} rows={jobs.map(j=>[j.display_id,j.name,j.customer_name,j.status,<button className="link" onClick={()=>setSelected(j.id)}>Open editor</button>])} headers={["ID","Job","Customer","Status",""]}/>{job&&<EstimateEditor job={job} catalog={catalog} notify={notify}/>}</> }
function EstimateEditor({job,catalog,notify}:{job:Job;catalog:CatalogItem[];notify:(v:string)=>void}) { const [lines,setLines]=useState<Array<{id:string;description:string;quantity:number;unit:string;unitPriceCents:number}>>([]); const [catalogId,setCatalogId]=useState(""); const load=()=>api<{data:typeof lines}>(`/jobs/${job.id}/line-items`).then(r=>setLines(r.data)); useEffect(()=>{void load()},[job.id]); const add=async()=>{const item=catalog.find(i=>i.id===catalogId);if(!item)return;await api(`/jobs/${job.id}/line-items`,{method:"POST",body:JSON.stringify({catalogItemId:item.id,position:lines.length,description:item.description,details:null,skuOrModel:null,unit:item.unit,quantity:1,unitPriceCents:item.defaultPriceCents})});await load()}; const generate=async()=>{try{await api(`/jobs/${job.id}/estimates`,{method:"POST",body:JSON.stringify({notes:null,adjustments:[]})});notify("Estimate generated in PDF, XLSX, and CSV.")}catch(e){notify(e instanceof Error?e.message:"Generation failed")}}; return <section className="panel editor"><div className="panel-title"><div><p className="eyebrow">ESTIMATE EDITOR</p><h2>{job.display_id} · {job.name}</h2></div><button onClick={()=>void generate()}>Generate estimate</button></div><div className="catalog-pick"><select value={catalogId} onChange={e=>setCatalogId(e.target.value)}><option value="">Copy an item from catalog…</option>{catalog.filter(i=>i.active).map(i=><option key={i.id} value={i.id}>{i.description} · {money(i.defaultPriceCents)}/{i.unit}</option>)}</select><button className="secondary" onClick={()=>void add()}>Add line</button></div>{lines.map(line=><div className="line" key={line.id}><strong>{line.description}</strong><span>{line.quantity} {line.unit}</span><b>{money(line.quantity*line.unitPriceCents)}</b></div>)}</section> }
function Catalog({items,busy,submit}:{items:CatalogItem[];busy:boolean;submit:(v:object)=>Promise<void>}) { return <Grid title="Reusable catalog" form={<SimpleForm busy={busy} fields={["description","unit","defaultPrice"]} transform={v=>({...v,defaultPriceCents:Math.round(Number(v.defaultPrice)*100),active:true,notes:null})} submit={submit}/>} rows={items.map(i=>[i.description,i.unit,money(i.defaultPriceCents),i.active?"Active":"Archived"])} headers={["Description","Unit","Default price","Status"]}/> }
function Estimates({estimates}:{estimates:Estimate[]}) { return <Grid title="Immutable estimate history" rows={estimates.map(e=>[e.displayId,new Date(e.generatedAt).toLocaleDateString(),money(e.totalCents),"Stored privately"])} headers={["Estimate","Generated","Total","Artifacts"]}/> }
function Backups() { return <section className="panel"><p className="eyebrow">DATA PORTABILITY</p><h2>Full account export</h2><p className="muted">Download relational CSVs and a relationship manifest. Nightly SQL recovery copies are retained separately in private R2.</p><a className="button" href="/api/v1/export">Download full ZIP export</a></section> }
function Settings() { return <section className="panel"><p className="eyebrow">SECURITY & BRAND</p><h2>Workspace settings</h2><div className="settings-row"><span>Authorized identity</span><strong>proangleconstruction@gmail.com</strong></div><div className="settings-row"><span>Brand</span><strong>Pro Angle Construction</strong></div><div className="settings-row"><span>Default document format</span><strong>US Letter</strong></div></section> }
function Grid({title,form,rows,headers}:{title:string;form?:React.ReactNode;rows:Array<Array<React.ReactNode>>;headers:string[]}) { return <section className="panel"><div className="panel-title"><div><p className="eyebrow">WORKSPACE</p><h2>{title}</h2></div>{form}</div>{rows.length?<div className="data-grid"><div className="grid-row grid-head">{headers.map(h=><span key={h}>{h}</span>)}</div>{rows.map((row,i)=><div className="grid-row" key={i}>{row.map((cell,j)=><span key={j}>{cell}</span>)}</div>)}</div>:<Empty title={`No ${title.toLowerCase()} yet`} text="Use the add button above to create the first record."/>}</section> }
function SimpleForm({fields,selects={},busy,submit,transform=v=>v}:{fields:string[];selects?:Record<string,[string,string][]>;busy:boolean;submit:(v:object)=>Promise<void>;transform?:(v:Record<string,string>)=>object}) { const [open,setOpen]=useState(false); const onSubmit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;await submit(transform(values));setOpen(false)}; return <>{<button onClick={()=>setOpen(true)}>+ Add new</button>}{open&&<div className="modal" onMouseDown={()=>setOpen(false)}><form onSubmit={e=>void onSubmit(e)} onMouseDown={e=>e.stopPropagation()}><h2>Add record</h2>{fields.map(field=><label key={field}>{field.replace(/([A-Z])/g," $1")}{selects[field]?<select name={field} required><option value="">Select…</option>{selects[field].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:field==="scope"?<textarea name={field}/>:<input name={field} type={field==="email"?"email":field==="defaultPrice"?"number":"text"} step="0.01" required={["name","description","unit","customerId","defaultPrice"].includes(field)}/>}</label>)}<div className="actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy}>Save</button></div></form></div>}</> }
function Empty({title,text}:{title:string;text:string}) { return <div className="empty"><div>▤</div><h3>{title}</h3><p>{text}</p></div> }
