import { formatMoney } from "../domain/calculations";
import type { AdjustmentInput, EstimateSnapshot } from "../domain/contracts";

const esc = (value: unknown) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const label = (kind: AdjustmentInput["kind"]) => ({ markup: "Markup", discount: "Discount", tax: "Tax", deposit: "Deposit" })[kind];

export function estimateHtml(s: EstimateSnapshot): string {
  const adjustmentRows = s.adjustments.map((adjustment) => {
    const amount = adjustment.kind === "markup" ? s.totals.markupCents : adjustment.kind === "discount" ? -s.totals.discountCents : adjustment.kind === "tax" ? s.totals.taxCents : -s.totals.depositCents;
    return `<div><span>${label(adjustment.kind)}</span><strong>${formatMoney(amount)}</strong></div>`;
  }).join("");
  const rows = s.lines.map((line) => `<tr><td><strong>${esc(line.description)}</strong>${line.details ? `<small>${esc(line.details)}</small>` : ""}${line.skuOrModel ? `<small>SKU / Model: ${esc(line.skuOrModel)}</small>` : ""}</td><td>${esc(line.quantity)}</td><td>${esc(line.unit)}</td><td>${formatMoney(line.unitPriceCents)}</td><td>${formatMoney(line.amountCents)}</td></tr>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><style>
  @page{size:Letter;margin:.55in .55in .72in}.continuation{display:none}*{box-sizing:border-box}body{margin:0;color:#102f49;font-family:Arial,sans-serif;font-size:11px}.mast{height:150px;border-bottom:4px solid #123d5c;display:flex;align-items:center;justify-content:space-between}.brand{font-size:32px;font-weight:800;letter-spacing:2px}.brand span{color:#777}.construction{font-size:11px;letter-spacing:6px;text-align:center}.contact{font-size:13px;line-height:1.5;border-left:1px solid #777;padding-left:30px}.byline{text-align:center;font-weight:700;margin:12px}.title{text-align:center}.title h1{font-size:23px;margin:0 0 8px}.title p{color:#555;margin:0}.blocks{margin-top:34px}.block{margin:0 0 25px;break-inside:avoid}.block h2,.items h2{font-size:14px;margin:0 0 8px}.block p{white-space:pre-line;color:#111;margin:0;line-height:1.45}.scope{font-weight:700}.items{margin-top:28px}table{border-collapse:collapse;width:100%;font-size:10.5px}thead{display:table-header-group;background:#e7eef3}tfoot{display:table-footer-group;height:34px}tfoot td{border:0;background:white}th,td{border:1px solid #dbe4eb;padding:7px 5px;text-align:left;vertical-align:top}th:nth-child(2),td:nth-child(2),th:nth-child(4),td:nth-child(4),th:nth-child(5),td:nth-child(5){text-align:right}tbody tr{break-inside:avoid}tbody tr:nth-child(even){background:#f5f7f8}td small{display:block;font-weight:700;margin-top:3px}.totals{margin:20px 0 0 auto;width:245px;break-inside:avoid;color:#111}.totals div{display:flex;justify-content:space-between;padding:4px}.totals .grand{font-size:15px;color:#102f49}.notes{margin-top:25px;white-space:pre-line;break-inside:avoid}.footer{position:fixed;bottom:0;left:0;right:0;text-align:center;background:#0b2f49;color:white;padding:9px;font-size:8px;letter-spacing:2px}.page{font-size:8px}@media print{.continuation{display:table-header-group}}
  </style></head><body><header class="mast"><div><div class="brand">PRO <span>ANGLE</span></div><div class="construction">CONSTRUCTION</div></div><div class="contact">188 Kaider Road<br>Uniontown, PA 15401<br><br>440.429.3474</div></header><div class="byline">Kevin Edinger&nbsp; | &nbsp;proangleconstruction@gmail.com</div><section class="title"><h1>ESTIMATE</h1><p>Estimate ID: ${esc(s.displayId)} &nbsp;&nbsp; Date: ${esc(new Date(s.generatedAt).toLocaleDateString("en-US", { timeZone: "America/New_York" }))}</p></section><section class="blocks"><div class="block"><h2>CUSTOMER</h2><p>Customer ID: ${esc(s.customer.displayId)}\n${esc(s.customer.name)}\n${esc(s.customer.phone)}\n${esc(s.customer.email)}\n${esc(s.customer.address)}</p></div><div class="block"><h2>JOB</h2><p>Job ID: ${esc(s.job.displayId)}\n${esc(s.job.name)}\n${esc(s.job.address)}</p></div><div class="block"><h2>SCOPE OF WORK</h2><p class="scope">${esc(s.job.scope)}</p></div></section><section class="items"><h2>LINE ITEMS</h2><table><thead><tr><th>Item / Reference</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Amount</th></tr></thead><tfoot><tr><td colspan="5"></td></tr></tfoot><tbody>${rows}</tbody></table></section><div class="totals"><div><span>Subtotal</span><strong>${formatMoney(s.totals.subtotalCents)}</strong></div>${adjustmentRows}<div class="grand"><strong>TOTAL</strong><strong>${formatMoney(s.totals.totalCents)}</strong></div>${s.totals.depositCents ? `<div><span>Balance due</span><strong>${formatMoney(s.totals.balanceDueCents)}</strong></div>` : ""}</div>${s.notes ? `<div class="notes"><strong>NOTES</strong><br>${esc(s.notes)}</div>` : ""}<footer class="footer">BUILDING A STRONGER TOMORROW &nbsp; | &nbsp; RESIDENTIAL &nbsp; COMMERCIAL &nbsp; RENOVATIONS &nbsp; ADDITIONS <span class="page"></span></footer></body></html>`;
}
