import { formatMoney } from "../domain/calculations";
import type { AdjustmentInput, EstimateSnapshot } from "../domain/contracts";
import estimateHeader from "./assets/estimate-header.jpg?inline";

const esc = (value: unknown) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const label = (kind: AdjustmentInput["kind"]) => ({ markup: "Markup", discount: "Discount", tax: "Tax", deposit: "Deposit" })[kind];

export function estimateHtml(s: EstimateSnapshot): string {
  const adjustmentRows = s.adjustments.map((adjustment) => {
    const amount = adjustment.kind === "markup" ? s.totals.markupCents : adjustment.kind === "discount" ? -s.totals.discountCents : adjustment.kind === "tax" ? s.totals.taxCents : -s.totals.depositCents;
    return `<div><span>${label(adjustment.kind)}</span><strong>${formatMoney(amount)}</strong></div>`;
  }).join("");
  const row = (line: EstimateSnapshot["lines"][number]) => `<tr><td><strong>${esc(line.description)}</strong>${line.details ? `<small>${esc(line.details)}</small>` : ""}${line.skuOrModel ? `<small>SKU / Model: ${esc(line.skuOrModel)}</small>` : ""}</td><td>${esc(line.quantity)}</td><td>${esc(line.unit)}</td><td>${formatMoney(line.unitPriceCents)}</td><td>${formatMoney(line.amountCents)}</td></tr>`;
  const firstRows = s.lines.slice(0, 3).map(row).join("");
  const continuationRows = s.lines.slice(3).map(row).join("");
  const totals = `<div class="totals"><div><span>Subtotal</span><strong>${formatMoney(s.totals.subtotalCents)}</strong></div>${adjustmentRows}<div class="grand"><strong>TOTAL</strong><strong>${formatMoney(s.totals.totalCents)}</strong></div>${s.totals.depositCents ? `<div><span>Balance due</span><strong>${formatMoney(s.totals.balanceDueCents)}</strong></div>` : ""}</div>`;
  const notes = s.notes ? `<div class="notes"><strong>NOTES</strong><br>${esc(s.notes)}</div>` : "";
  const table = (rows: string) => `<table><thead><tr><th>Item / Reference</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Amount</th></tr></thead><tfoot><tr><td colspan="5"></td></tr></tfoot><tbody>${rows}</tbody></table>`;
  return `<!doctype html><html><head><meta charset="utf-8"><style>
  @page{size:Letter;margin:.36in .55in .55in}*{box-sizing:border-box}body{margin:0;color:#102f49;font-family:Arial,sans-serif;font-size:11px}.first-page{position:relative}.first-page.has-continuation{height:10.04in;break-after:page}.mast{position:relative;width:100%}.mast img{display:block;width:100%;height:auto}.brand-fix{position:absolute;left:6%;top:71%;width:43%;height:10.5%;display:flex;align-items:center;justify-content:center;background:white;color:#17334a;font-size:11px;letter-spacing:5px}.byline{text-align:center;font-weight:700;margin:8px 12px 12px}.title{text-align:center}.title h1{font-size:23px;margin:0 0 8px}.title p{color:#555;margin:0}.blocks{margin-top:34px}.block{margin:0 0 25px;break-inside:avoid}.block h2,.items h2,.continuation-page h2{font-size:14px;margin:0 0 8px}.block p{white-space:pre-line;color:#111;margin:0;line-height:1.45}.scope{font-weight:700}.items{margin-top:28px}table{border-collapse:collapse;width:100%;font-size:10.5px}thead{display:table-header-group;background:#e7eef3}tfoot{display:table-footer-group;height:20px}tfoot td{border:0;background:white}th,td{border:1px solid #dbe4eb;padding:7px 5px;text-align:left;vertical-align:top}th:nth-child(2),td:nth-child(2),th:nth-child(4),td:nth-child(4),th:nth-child(5),td:nth-child(5){text-align:right}tbody tr{break-inside:avoid}tbody tr:nth-child(even){background:#f5f7f8}td small{display:block;font-weight:700;margin-top:3px}.totals{margin:20px 0 0 auto;width:245px;break-inside:avoid;color:#111}.totals div{display:flex;justify-content:space-between;padding:4px}.totals .grand{font-size:15px;color:#102f49}.notes{margin-top:25px;white-space:pre-line;break-inside:avoid}.footer{position:absolute;bottom:0;left:0;right:0;background:#0b2f49;color:white;text-align:center;padding:7px 12px;font-size:7px;letter-spacing:2px;line-height:1.7}.footer strong{font-weight:500;font-size:8px;letter-spacing:3px}.continuation-page{break-before:page}.continuation-page>.byline{margin-top:0}.continuation-page h2{margin-top:10px}
  </style></head><body><section class="first-page${continuationRows ? " has-continuation" : ""}"><header class="mast"><img src="${estimateHeader}" alt="Pro Angle Construction, 188 Kaider Road, Uniontown PA 15401, 440.429.3474"><span class="brand-fix">CONSTRUCTION</span></header><div class="byline">Kevin Edinger&nbsp; | &nbsp;proangleconstruction@gmail.com</div><section class="title"><h1>ESTIMATE</h1><p>Estimate ID: ${esc(s.displayId)} &nbsp;&nbsp; Date: ${esc(new Date(s.generatedAt).toLocaleDateString("en-US", { timeZone: "America/New_York" }))}</p></section><section class="blocks"><div class="block"><h2>CUSTOMER</h2><p>Customer ID: ${esc(s.customer.displayId)}\n${esc(s.customer.name)}\n${esc(s.customer.phone)}\n${esc(s.customer.email)}\n${esc(s.customer.address)}</p></div><div class="block"><h2>JOB</h2><p>Job ID: ${esc(s.job.displayId)}\n${esc(s.job.name)}\n${esc(s.job.address)}</p></div><div class="block"><h2>SCOPE OF WORK</h2><p class="scope">${esc(s.job.scope)}</p></div></section><section class="items"><h2>LINE ITEMS</h2>${table(firstRows)}</section>${continuationRows ? "" : totals + notes}<footer class="footer"><strong>BUILDING A STRONGER TOMORROW</strong><br>RESIDENTIAL &nbsp; | &nbsp; COMMERCIAL &nbsp; | &nbsp; RENOVATIONS &nbsp; | &nbsp; ADDITIONS &nbsp; | &nbsp; GENERAL CONTRACTING</footer></section>${continuationRows ? `<section class="continuation-page"><div class="byline">Kevin Edinger&nbsp; | &nbsp;proangleconstruction@gmail.com</div><h2>LINE ITEMS - CONTINUED</h2>${table(continuationRows)}${totals}${notes}</section>` : ""}</body></html>`;
}
